access-token:
  private: "access-refresh-token-keys/access-token-private.key"
  public: "access-refresh-token-keys/access-token-public.key"
refresh-token:
  private: "access-refresh-token-keys/refresh-token-private.key"
  public: "access-refresh-token-keys/refresh-token-public.key"
spring:
  data:
    mongodb:
      uri: mongodb+srv://dabedip595:root@cluster0.oeolccr.mongodb.net/test_paf?retryWrites=true&w=majority&appName=Cluster0
server:
  port: 8090

logging:
  level:
    org.springframework.security: DEBUG
